# .github/workflows/ci.yml
name: Python application

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  PYTHON_VERSION: "3.10"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install flake8

      - name: Syntax check (py_compile)
        run: |
          python -m py_compile $(git ls-files '*.py' || echo "")

      - name: Lint (flake8)
        run: |
          flake8 . --count --select=E,F,W --max-complexity=10 --max-line-length=127 --show-source --statistics

  tests:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: pytest -v

  docker_build:
    runs-on: ubuntu-latest
    needs: [lint, tests]
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Check Dockerfile presence
        id: df
        run: |
          if [ -f Dockerfile ]; then
            echo "found=true" >> $GITHUB_OUTPUT
          else
            echo "found=false" >> $GITHUB_OUTPUT
          fi

      - name: Docker meta
        if: steps.df.outputs.found == 'true'
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: myorg/myapp
          tags: |
            type=ref,event=branch
            type=sha

      - name: Set up QEMU
        if: steps.df.outputs.found == 'true'
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        if: steps.df.outputs.found == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker registry (optional)
        if: steps.df.outputs.found == 'true' && env.DOCKERHUB_USERNAME != '' && env.DOCKERHUB_TOKEN != ''
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Build (and optionally push)
        if: steps.df.outputs.found == 'true'
        uses: docker/build-push-action@v6
        with:
          context: .
          # пушим только при пуше в main и когда есть токен
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && env.DOCKERHUB_TOKEN != '' }}
          # если НЕ пушим — загружаем образ в локальный docker-daemon для последующего docker run
          load: ${{ !(github.event_name == 'push' && github.ref == 'refs/heads/main' && env.DOCKERHUB_TOKEN != '') }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Verify container starts and responds (script)
        if: steps.df.outputs.found == 'true'
        env:
          IMAGE_TAGS: ${{ steps.meta.outputs.tags }}
          PORT: "8000"
          HEALTH_PATH: "/health"
          STARTUP_TIMEOUT: "20"
          CONTAINER_NAME: "app-test"
        run: bash scripts/verify_container.sh