name: FastAPI CI/CD

on:
  push:
    branches: [ Parse_Service_Steam, development, TestBranchCiCD]
  pull_request:
    branches: [ Parse_Service_Steam, TestBranchCiCD]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-asyncio httpx requests
        
    - name: Run unit tests
      run: |
        python -m pytest tests/ -v
        
    - name: Verify imports and basic functionality
      run: |
        python -c "from app.main import app; print('FastAPI app imported successfully')"
        python -c "from app.routers.main import router; print('Main router imported successfully')"
        python -c "from app.routers.search import router; print('Search router imported successfully')"
        python -c "from app.services.steam_service import SteamDataService; print('Steam service imported successfully')"
        
    - name: Check template files
      run: |
        echo "Checking template files:"
        find app/templates -name "*.html" | head -10
        echo "Templates check completed"
        
    - name: Start server
      run: |
        # Запускает сервер в фоне
        timeout 30s python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 || echo "Server test completed"